[package]
name = "lumora"
version = "0.1.0"
description = "lumora — light up your literature."
authors = ["lumora"]
edition = "2021"

[lib]
name = "lumora_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
reqwest = { version = "0.13", default-features = false, features = ["rustls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = [] }
