ALTER TABLE "Paper" ADD COLUMN "documentType" TEXT;
ALTER TABLE "Paper" ADD COLUMN "tags" JSONB NOT NULL DEFAULT '[]';
ALTER TABLE "Paper" ADD COLUMN "keywords" JSONB NOT NULL DEFAULT '[]';
ALTER TABLE "Paper" ADD COLUMN "url" TEXT;
ALTER TABLE "Paper" ADD COLUMN "pages" TEXT;
ALTER TABLE "Paper" ADD COLUMN "volume" TEXT;
ALTER TABLE "Paper" ADD COLUMN "issue" TEXT;
ALTER TABLE "Paper" ADD COLUMN "publisher" TEXT;
